// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: dispatch/reporting/v1/reporting.proto

package reportingv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/siropaca/dispatch/backend/internal/proto/dispatch/reporting/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ReportingServiceName is the fully-qualified name of the ReportingService service.
	ReportingServiceName = "dispatch.reporting.v1.ReportingService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ReportingServiceRunReportingProcedure is the fully-qualified name of the ReportingService's
	// RunReporting RPC.
	ReportingServiceRunReportingProcedure = "/dispatch.reporting.v1.ReportingService/RunReporting"
)

// ReportingServiceClient is a client for the dispatch.reporting.v1.ReportingService service.
type ReportingServiceClient interface {
	RunReporting(context.Context, *connect.Request[v1.RunReportingRequest]) (*connect.Response[v1.RunReportingResponse], error)
}

// NewReportingServiceClient constructs a client for the dispatch.reporting.v1.ReportingService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewReportingServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ReportingServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	reportingServiceMethods := v1.File_dispatch_reporting_v1_reporting_proto.Services().ByName("ReportingService").Methods()
	return &reportingServiceClient{
		runReporting: connect.NewClient[v1.RunReportingRequest, v1.RunReportingResponse](
			httpClient,
			baseURL+ReportingServiceRunReportingProcedure,
			connect.WithSchema(reportingServiceMethods.ByName("RunReporting")),
			connect.WithClientOptions(opts...),
		),
	}
}

// reportingServiceClient implements ReportingServiceClient.
type reportingServiceClient struct {
	runReporting *connect.Client[v1.RunReportingRequest, v1.RunReportingResponse]
}

// RunReporting calls dispatch.reporting.v1.ReportingService.RunReporting.
func (c *reportingServiceClient) RunReporting(ctx context.Context, req *connect.Request[v1.RunReportingRequest]) (*connect.Response[v1.RunReportingResponse], error) {
	return c.runReporting.CallUnary(ctx, req)
}

// ReportingServiceHandler is an implementation of the dispatch.reporting.v1.ReportingService
// service.
type ReportingServiceHandler interface {
	RunReporting(context.Context, *connect.Request[v1.RunReportingRequest]) (*connect.Response[v1.RunReportingResponse], error)
}

// NewReportingServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewReportingServiceHandler(svc ReportingServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	reportingServiceMethods := v1.File_dispatch_reporting_v1_reporting_proto.Services().ByName("ReportingService").Methods()
	reportingServiceRunReportingHandler := connect.NewUnaryHandler(
		ReportingServiceRunReportingProcedure,
		svc.RunReporting,
		connect.WithSchema(reportingServiceMethods.ByName("RunReporting")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dispatch.reporting.v1.ReportingService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ReportingServiceRunReportingProcedure:
			reportingServiceRunReportingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedReportingServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedReportingServiceHandler struct{}

func (UnimplementedReportingServiceHandler) RunReporting(context.Context, *connect.Request[v1.RunReportingRequest]) (*connect.Response[v1.RunReportingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("dispatch.reporting.v1.ReportingService.RunReporting is not implemented"))
}
